//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusUpdatesModel
{
    using System;
    
    public enum Phases : int
    {
        Start_Up = 0,
        Solution_Outline = 1,
        Macro_Design = 2,
        Micro_Design = 3,
        Build_Test = 4,
        Deploy = 5,
        Transition_Close = 6
    }
}
