//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusUpdatesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectPhase
    {
        public int PhaseID { get; set; }
        public System.Guid ProjectID { get; set; }
        public string UpdateKey { get; set; }
        public Nullable<int> UpdateCount { get; set; }
        public Nullable<System.DateTime> LatestUpdate { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Project Project { get; set; }
    }
}
