//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusUpdatesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusUpdate
    {
        public System.Guid ProjectID { get; set; }
        public System.Guid ProjectUpdateID { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public Nullable<int> VerticalID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string UpdateKey { get; set; }
        public string UpdateValue { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectUpdate ProjectUpdate { get; set; }
        public virtual Vertical Vertical { get; set; }
    }
}
