//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatusUpdatesModel
{
    using System;
    
    public enum Verticals : int
    {
        Warehouse_Solutions = 0,
        Merchandising_Solutions = 1,
        Membership_Solutions = 2,
        Distribution_Solutions = 3,
        International_Solutions = 4,
        Ancillary_Solutions = 5,
        eBusiness_Soluttions = 6,
        Corporate_Solutions = 7
    }
}
